name: Reusable workflow
on:
  workflow_call:
    inputs:
      who-to-greet:
        type: string
        required: true
        default: World
jobs:
  reusable-job:
    runs-on: ubuntu-latest
    steps:
      - name: Greeting
        run: echo "Hello ${{ inputs.who-to-greet }}"
